# Generated by Django 4.0.4 on 2022-05-21 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title project')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/projects', verbose_name='image project')),
                ('definition', models.TextField(blank=True, null=True, verbose_name='definition project')),
                ('cost_investments', models.FloatField(verbose_name='investments project')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('age_business', models.FloatField(blank=True, null=True, verbose_name='age business')),
                ('number_employees', models.IntegerField(default=1, verbose_name='the number of employees')),
                ('organizational_type', models.CharField(default='OOO', help_text='its legal status and business goals arising from this', max_length=250, verbose_name='Organizational and legal form')),
                ('business_type', models.CharField(choices=[('STARTUP', 'Start up'), ('FRANCHISE', 'Franchise'), ('READY BUSINESSES', 'Ready businesses')], default='STARTUP', max_length=250)),
                ('id_delete', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
