# Generated by Django 4.0.4 on 2022-05-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_specialization_user_rate_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/users'),
        ),
    ]
